---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(nbastatR)
library(tidyverse)
```



```{r}
glossary <- dictionary_nba_names()

covid_season_month_before <- teams_players_stats(seasons = 2020, measures = "Advanced", types = "team", tables = "general", modes = "PerGame", date_from = "2-11-20", date_to = "3-11-20") %>% 
  unnest(dataTable) %>% 
  mutate(df_type = "month_before")

covid_season <- teams_players_stats(seasons = 2020, measures = "Advanced", types = "team", tables = "general", modes = "PerGame", date_from = "10-22-19", date_to = "3-11-20") %>% 
  unnest(dataTable) %>% 
  mutate(df_type = "all_before")
  
bubble <- teams_players_stats(seasons = 2020, measures = "Advanced",  types = "team", season_types = c("Regular Season", "Playoffs"), tables = "general", modes = "PerGame", date_from = "7-29-20", date_to = "10-11-20") %>% 
  unnest(dataTable) 

bubble_seeding <- bubble %>% 
  filter(typeSeason == "Regular Season") %>% 
  mutate(df_type = "bubble_seeding") 

bubble_playoffs <- bubble %>% 
  filter(typeSeason == "Playoffs") %>% 
  mutate(df_type = "bubble_playoffs")   

#covid_season_plus_bubble_seeding <- teams_players_stats(seasons = 2020, measures = "Advanced", types = "team", tables = "general", modes = "PerGame", date_from = "10-22-19", date_to = "10-11-20")%>% 
#  unnest(dataTable) %>% 
#  mutate(df_type = "all_before_plus_bubble")



```

```{r}
teams <- nba_teams() %>% 
  select(-nameTeam)

bubble_teams <- bubble %>% 
  group_by(nameTeam, idTeam) %>% 
  summarize() %>% 
  left_join(teams)
  
bubble_stats_long <- bind_rows(covid_season_month_before,
                               #covid_season,
                               bubble_seeding,
                               bubble_playoffs,
                               ) %>%
                               select(nameTeam:paceE,
                                      df_type,
                                      -contains("rank")) %>%
                                 pivot_longer(gp:paceE, names_to = "rating", values_to = "value") %>%
                                 semi_join(bubble_teams, by = "nameTeam") #only teams that were invited to bubble

bubble_stats_long %>% 
  filter(rating == "ortg",
         #df_type != "bubble_playoffs"
         ) %>% 
  mutate(ordered_teams = fct_reorder2(nameTeam, df_type == "month_before", value, .desc = FALSE)) %>% 
  ggplot(aes(y = ordered_teams, x = value, color = df_type)) + 
  geom_point() +
  scale_color_manual(values = c("month_before" = "#00bcd4",
                              "bubble_seeding" = "#ff9800", 
                              "bubble_playoffs" = "#e91e63"),
                     name = "Time Period") +
  xlab("Offensive Rating") + 
  ylab(NULL)

bubble_stats_long %>% 
  filter(rating == "drtg",
         #df_type != "bubble_playoffs",
         ) %>%
  mutate(ordered_teams = fct_reorder2(nameTeam, df_type == "month_before", value)) %>% 
  ggplot(aes(y = ordered_teams, x = value, color = df_type)) + 
  geom_point() +
  scale_x_reverse() +
  scale_color_manual(values=c("month_before" = "#00bcd4",
                              "bubble_seeding" = "#ff9800", 
                              "bubble_playoffs" = "#e91e63")) +
  xlab("Defensive Rating") + 
  ylab(NULL)

bubble_stats_long %>% 
  filter(rating == "netrtg",
        # df_type != "bubble_playoffs",
         ) %>%
  mutate(ordered_teams = fct_reorder2(nameTeam, df_type == "month_before", value, .desc = FALSE)) %>% 
  ggplot(aes(y = ordered_teams, x = value, color = df_type)) + 
  geom_point() +
  scale_color_manual(values = c("month_before" = "#00bcd4",
                              "bubble_seeding" = "#ff9800", 
                              "bubble_playoffs" = "#e91e63")) +
  xlab("Net Rating (Offensive - Defensive)") + 
  ylab(NULL)
 
bubble_stats_long %>% 
  filter(rating %in% c(
                        "pctAST",				
                        "pctDREB",				
                        "pctEFG",				
                        "pctOREB",				
                        "pctTOVTeam",				
                        "pctTREB",				
                        "pctTS"
                          )
         ) %>% 
  group_by(df_type, rating) %>% 
  summarize(avg = mean(value)) %>% 
  ggplot(aes(x = rating, y = avg, fill = df_type)) + 
  geom_bar(stat = "identity", position = "dodge")


bubble_stats_long %>% 
  group_by(rating) %>% 
  summarize()
```

```{r}

season_2019_p1 <- teams_players_stats(seasons = 2019, measures = "Advanced", season_types =  "Regular Season", types = "team", tables = "general", modes = "PerGame", date_from = "10-10-18", date_to = "3-22-19") %>% 
  unnest(dataTable) 
season_2019_p2 <- teams_players_stats(seasons = 2019, measures = "Advanced", season_types =  "Regular Season", types = "team", tables = "general", modes = "PerGame", date_from = "10-10-18", date_to = "3-23-19") %>% 
  unnest(dataTable) 
season_2019_p3 <- teams_players_stats(seasons = 2019, measures = "Advanced", season_types =  "Regular Season", types = "team", tables = "general", modes = "PerGame", date_from = "10-10-18", date_to = "3-24-19") %>% 
  unnest(dataTable)
season_2019_p4 <- teams_players_stats(seasons = 2019, measures = "Advanced", season_types = "Regular Season", types = "team", tables = "general", modes = "PerGame", date_from = "10-10-18", date_to = "3-25-19") %>% 
  unnest(dataTable)
season_2019_p5 <- teams_players_stats(seasons = 2019, measures = "Advanced", season_types = "Regular Season", types = "team", tables = "general", modes = "PerGame", date_from = "10-10-18", date_to = "3-26-19") %>% 
  unnest(dataTable)
season_2019_p6 <- teams_players_stats(seasons = 2019, measures = "Advanced", season_types = "Regular Season", types = "team", tables = "general", modes = "PerGame", date_from = "10-10-18", date_to = "3-27-19") %>% 
  unnest(dataTable)
season_2019_p7 <- teams_players_stats(seasons = 2019, measures = "Advanced", season_types = "Regular Season", types = "team", tables = "general", modes = "PerGame", date_from = "10-10-18", date_to = "3-28-19") %>% 
  unnest(dataTable) 

season_2019_74_games <- bind_rows(season_2019_p1,
                          season_2019_p2,
                          season_2019_p2,
                          season_2019_p4,
                         season_2019_p5,
                         season_2019_p6,
                         season_2019_p7
                         ) %>% 
  filter(gp == 74) %>% 
  select(nameTeam:paceE,
         -contains("rank")) %>% 
  unique() %>% 
  mutate(df_type = "first_74")

season_2019_month_before <- teams_players_stats(seasons = 2019, measures = "Advanced", season_types =  "Regular Season", types = "team", tables = "general", modes = "PerGame", date_from = "2-23-19", date_to = "3-23-19") %>% 
  unnest(dataTable) %>% 
  select(nameTeam:paceE,
         -contains("rank")) %>% 
  mutate(df_type = "month_before")


season_2019_last_8 <- teams_players_stats(seasons = 2019, measures = "Advanced", season_types =  c("Regular Season"), types = "team", tables = "general", modes = "PerGame", last_n_games = 8) %>% 
  unnest(dataTable) %>% 
  select(nameTeam:paceE,
         -contains("rank")) %>% 
  mutate(df_type = "last_8") 

season_2019_playoffs <- teams_players_stats(seasons = 2019, measures = "Advanced", season_types = "Regular Season", types = "team", tables = "general", modes = "PerGame", date_from = "10-10-18", date_to = "3-28-19") %>% 
  unnest(dataTable) %>% 
  select(nameTeam:paceE,
         -contains("rank")) %>% 
  mutate(df_type = "playoffs") 


season_19_long <- bind_rows(
          #season_2019_74_games,
          season_2019_month_before,
          season_2019_last_8,
          season_2019_playoffs,
          ) %>% 
  pivot_longer(gp:paceE, names_to = "rating", values_to = "value")  

season_19_long %>% 
  filter(rating == "ortg") %>% 
  semi_join(bubble_teams, by = "nameTeam") %>% #only teams that were invited to bubble
  mutate(ordered_teams = fct_reorder2(nameTeam, df_type == "month_before", value, .desc = FALSE)) %>% 
  ggplot(aes(y = ordered_teams, x = value, color = df_type)) + 
  geom_point()  +
  scale_color_manual(values = c("month_before" = "#00bcd4",
                              "last_8" = "#ff9800", 
                              "playoffs" = "#e91e63")) +
  xlab("Offensive Rating") + 
  ylab(NULL)

season_19_long %>% 
  filter(rating == "drtg") %>%
  semi_join(bubble_teams, by = "nameTeam") %>% 
  mutate(ordered_teams = fct_reorder2(nameTeam, df_type == "month_before", value)) %>% 
  ggplot(aes(y = ordered_teams, x = value, color = df_type)) + 
  geom_point() +
  scale_x_reverse() +  
  scale_color_manual(values = c("month_before" = "#00bcd4",
                              "last_8" = "#ff9800", 
                              "playoffs" = "#e91e63")) +
  xlab("Defensive Rating") + 
  ylab(NULL)

season_19_long %>% 
  filter(rating == "netrtg") %>% 
  semi_join(bubble_teams, by = "nameTeam") %>% #only teams that were invited to bubble
  mutate(ordered_teams = fct_reorder2(nameTeam, df_type == "month_before", value, .desc = FALSE)) %>% 
  ggplot(aes(y = ordered_teams, x = value, color = df_type)) + 
  geom_point()  +
  scale_color_manual(values = c("month_before" = "#00bcd4",
                              "last_8" = "#ff9800", 
                              "playoffs" = "#e91e63")) +
  xlab("Net Rating (Offensive - Defensive)") + 
  ylab(NULL)


season_19_long %>% 
  filter(rating == "ortg") %>% 
  semi_join(bubble_teams, by = "nameTeam") %>% #only teams that were invited to bubble
  mutate(ordered_teams = fct_reorder2(nameTeam, df_type == "first_74", value, .desc = FALSE)) %>% 
  ggplot(aes(y = ordered_teams, x = value, color = df_type)) + 
  geom_point() 

season_19_long %>% 
  filter(rating == "drtg") %>%
  semi_join(bubble_teams, by = "nameTeam") %>% 
  mutate(ordered_teams = fct_reorder2(nameTeam, df_type == "first_74", value)) %>% 
  ggplot(aes(y = ordered_teams, x = value, color = df_type)) + 
  geom_point() +
  scale_x_reverse()




season_19_long %>% 
  filter(rating %in% c(
                        "pctAST",				
                        "pctDREB",				
                        "pctEFG",				
                        "pctOREB",				
                        "pctTOVTeam",				
                        "pctTREB",				
                        "pctTS"
                          )
         ) %>% 
  group_by(df_type, rating) %>% 
  summarize(avg = mean(value)) %>% 
  ggplot(aes(x = rating, y = avg, fill = df_type)) + 
  geom_bar(stat = "identity", position = "dodge")



```



```{r fig.width = 8}

covid_players <- read_html("https://www.slamonline.com/nba/nba-coronavirus-covid-list/") %>% 
  html_element(css = ".wp-block-table") %>% 
  html_table(header = TRUE)

covid_players_fixed <- covid_players %>% 
  rename(name = "Player",
         date_reported = "Reported") %>% 
  mutate(team_abb = str_sub(name, -4, -2),
         name = str_remove(name, " \\(.+\\)"),
         date_reported = str_remove(date_reported, " \\(.+\\)"),
         date_reported = mdy(str_c(date_reported, " 2020")))

covid_season_players <- teams_players_stats(seasons = 2020, measures = "Advanced", types = "player", tables = "general", modes = "PerGame", date_from = "10-22-19", date_to = "3-11-20") %>% 
  unnest(dataTable) %>% 
  mutate(df_type = "all_before")

covid_season_players_month_before <- teams_players_stats(seasons = 2020, measures = "Advanced", types = "player", tables = "general", modes = "PerGame", date_from = "2-11-20", date_to = "3-11-20") %>% 
  unnest(dataTable) %>% 
  mutate(df_type = "month_before")

bubble_players <- teams_players_stats(seasons = 2020, measures = "Advanced",  types = "player", season_types = c("Regular Season", "Playoffs"), tables = "general", modes = "PerGame", date_from = "7-29-20", date_to = "10-11-20") %>% 
  unnest(dataTable)

bubble_seeding_players <- bubble_players %>%
  filter(typeSeason == "Regular Season") %>% 
  mutate(df_type = "bubble_seeding") 

bubble_playoffs_players <- bubble_players  %>%
  filter(typeSeason == "Playoffs") %>% 
  mutate(df_type = "bubble_playoffs") 

season_2019_players_playoffs <- teams_players_stats(seasons = 2019, measures = "Advanced",  season_types = c("Playoffs"), types = "player", tables = "general", modes = "PerGame") %>% 
  unnest(dataTable) %>% 
  mutate(df_type = "playoffs")

season_2019_players_month_before <- teams_players_stats(seasons = 2019, measures = "Advanced", types = "player", tables = "general", modes = "PerGame", date_from = "2-23-19", date_to = "3-23-19") %>% 
  unnest(dataTable) %>% 
  mutate(df_type = "month_before")


season_2019_players_last_8 <- teams_players_stats(seasons = 2019, measures = "Advanced",  types = "player", season_types = c("Regular Season"), tables = "general", modes = "PerGame", last_n_games = 8) %>% 
  unnest(dataTable) %>% 
  mutate(df_type = "last_8") 


bubble_season_combined <- bind_rows(
          covid_season_players_month_before,
          bubble_seeding_players,
          bubble_playoffs_players
          )

covid_players_fixed %>% 
  left_join(bubble_season_combined, by = c("name" = "namePlayer")) %>% 
  filter(!(name %in% c("Luc Mbah a Moute", "Jabari Parker"))) %>% #waived
  mutate(ordered_names = fct_reorder(name, date_reported, .desc = FALSE)) %>% 
  ggplot(aes(x = ordered_names, y = netrtg, color = df_type)) + 
  geom_point(alpha = .7) + 
  theme(axis.text.x = element_text(angle = 90)) +
  scale_color_manual(values=c("month_before" = "#00bcd4",
                              "bubble_seeding" = "#ff9800", 
                              "bubble_playoffs" = "#e91e63"))

season_2019_combined <- bind_rows(
          season_2019_players_month_before,
          season_2019_players_last_8,
          season_2019_players_playoffs
          ) 


covid_players_fixed %>% 
  left_join(season_2019_combined, by = c("name" = "namePlayer")) %>% 
 # semi_join(bind_rows(covid_season_players_month_before,
 #                     bubble_seeding_players),
 #           by = "namePlayer") %>% 
  filter(!(name %in% c("Luc Mbah a Moute", "Jabari Parker")))  %>% 
  mutate(ordered_names = fct_reorder(name, date_reported, .desc = FALSE)) %>% 
  ggplot(aes(x = ordered_names, y = netrtg, color = df_type)) + 
  geom_point(alpha = .7) + 
  theme(axis.text.x = element_text(angle = 90)) +
  scale_color_manual(values = c("month_before" = "#00bcd4",
                              "last_8" = "#ff9800", 
                              "playoffs" = "#e91e63")) 




```

```{r}

starters <- teams_players_stats(seasons = 2020, types = "player", starters_bench = list("Starters")) %>% 
  unnest(dataTable) 

top_guys_bubble <- starters %>% 
  #filter(gp > 25) %>% 
  semi_join(bubble_seeding_players, by = "namePlayer") %>% 
  semi_join(covid_season_players_month_before, by = "namePlayer") %>% 
  group_by(slugTeam) %>% 
  slice_max(gp, n = 7)

test <-  bubble_seeding_players %>% 
  semi_join(covid_season_players_month_before, by = "namePlayer") %>% 
  semi_join(starters, by = "namePlayer") 


top_guys_bubble %>% 
  group_by(slugTeam) %>% 
  summarize(count = n())



d3_data <- covid_season_players_month_before %>% 
  bind_rows(bubble_seeding_players) %>% 
  bind_rows(bubble_playoffs_players) %>% 
  semi_join(top_guys_bubble, by = "namePlayer") %>% 
  left_join(bubble_teams, by = "slugTeam") %>% 
  select(name = "namePlayer",
         team_abb = "slugTeam",
         team_name = "nameTeam",
         ortg,
         drtg,
         netrtg,
         df_type
         ) %>% 
  pivot_wider(names_from = "df_type", values_from = c("ortg", "drtg", "netrtg"))
 

  
covid_season_players_month_before %>% 
  bind_rows(bubble_seeding_players) %>% 
  bind_rows(bubble_playoffs_players) %>% 
  semi_join(top_guys_bubble, by = "namePlayer") %>% 
  left_join(bubble_teams, by = "slugTeam") %>% 
  select(name = "namePlayer",
         team_abb = "slugTeam",
         team_name = "nameTeam",
         ortg,
         drtg,
         netrtg,
         df_type
         ) %>% 
  ggplot(mapping = aes(x = drtg, y = ortg, color = df_type)) +
  geom_point() +
  scale_x_reverse()



d3_data %>%
  write_csv("data/d3_data.csv")

bubble_stats_long %>% 
  group_by(rating) %>% 
  summarize()
```



#
#```{r}
#
#season_2017_2019 <- teams_players_stats(seasons = 2017:2019, measures = "Advanced", season_types =  c("Regular Season", "Playoffs"), types = "team", tables = "general", modes = "PerGame", "3-24-19")
#
#season_2017_2019_last_8 <- teams_players_stats(seasons = 2017:2019, measures = "Advanced", season_types =  c("Regular Season"), types = "team", tables = "general", modes = "PerGame", last_n_games = 8)
#
#
#reg_2018 <- season_2017_2019$dataTable[[2]] %>% 
#  mutate(df_type = "regular_season")
#reg_2018_last_8 <- season_2017_2019_last_8$dataTable[[2]] %>% 
#  mutate(df_type = "regular_season_last_8")
#playoffs_2018 <- season_2017_2019$dataTable[[5]] %>% 
#  mutate(df_type = "playoffs")
#
#reg_2017 <- season_2017_2019$dataTable[[1]] %>% 
#  mutate(df_type = "regular_season")
#reg_2017_last_8 <- season_2017_2019_last_8$dataTable[[3]] %>% 
#  mutate(df_type = "regular_season_last_8")
#playoffs_2017 <- season_2017_2019$dataTable[[4]] %>% 
#  mutate(df_type = "playoffs")
#
#
#
##bind_rows(reg_2019,
##          reg_2019_last_8,
##          #playoffs_2019
##          ) %>% 
##  semi_join(playoffs_2019, by = "nameTeam") %>% 
##  mutate(ordered_teams = fct_reorder2(nameTeam, df_type == "regular_season", ortg, .desc = FALSE)) %>% 
##  ggplot(aes(y = ordered_teams, x = ortg, color = df_type)) + 
##  geom_point()
#
#
#
#bind_rows(reg_2018,
#          reg_2018_last_8,
#          #playoffs_2018
#          ) %>% 
#  #semi_join(playoffs_2018, by = "nameTeam") %>% 
#  mutate(ordered_teams = fct_reorder2(nameTeam, df_type == "regular_season", netrtg, .desc = FALSE)) %>% 
#  ggplot(aes(y = ordered_teams, x = netrtg, color = df_type)) + 
#  geom_point()
#
#
#bind_rows(reg_2017,
#          reg_2017_last_8,
#          #playoffs_2018
#          ) %>% 
#  #semi_join(playoffs_2018, by = "nameTeam") %>% 
#  mutate(ordered_teams = fct_reorder2(nameTeam, df_type == "regular_season", netrtg, .desc = FALSE)) %>% 
#  ggplot(aes(y = ordered_teams, x = netrtg, color = df_type)) + 
#  geom_point()
#
#
#
#```




